/**
 * 因redux是一個global state 所以每個action命名都應是唯一的
 * 全部acton 集中在這裡，避免檔案分散造成命名衝突
 */

export const FETCH_INITIAL_API_SAGA = 'FETCH_INITIAL_API_SAGA'
export const FETCH_LIST_API_SAGA = 'FETCH_LIST_API_SAGA'
export const FETCH_LIST_API_SUCCESS = 'FETCH_LIST_API_SUCCESS'
export const FETCH_FAVOR_LIST_SUCCESS = 'FETCH_FAVOR_LIST_SUCCESS'
export const SET_LOADING = 'SET_LOADING'
export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'

//login
export const FETCH_IS_LOGIN_SAGA = 'FETCH_IS_LOGIN_SAGA'
export const FETCH_LOGIN_SAGA = 'FETCH_LOGIN_SAGA'
export const FETCH_LOGIN_SAGA_SUCCESS = 'FETCH_LOGIN_SAGA_SUCCESS'
export const FETCH_LOGOUT_SAGA = 'FETCH_LOGOUT_SAGA'
export const FETCH_LOGOUT_SAGA_SUCCESS = 'FETCH_LOGOUT_SAGA_SUCCESS'
export const HANDLE_CHANGE_ACCOUNT = 'HANDLE_CHANGE_ACCOUNT'
export const HANDLE_CHANGE_PASSWORD = 'HANDLE_CHANGE_PASSWORD'
export const UPDATE_LIST_DATA = 'UPDATE_LIST_DATA'
export const SELECTED_LIST = 'SELECTED_LIST'
export const ON_CHANGE_REGISTER_INPUT = 'ON_CHANGE_REGISTER_INPUT'
export const FETCH_FAVOR_POST_SAGA = 'FETCH_FAVOR_POST_SAGA'
export const FETCH_UN_FAVOR_POST_SAGA = 'FETCH_UN_FAVOR_POST_SAGA'
